---
# yes / no values only react to true, otherwise they are ignored
reduce_telemetry: true
file_explorer:
    unhide_hidden_files: true
    unhide_file_extensions: true
    unhide_superhidden_files: false
    unhide_full_path_in_title: true
task_bar:
    search_bar_mode: hidden # full / icon / hidden
    hide_task_view: true
theme:
    dark_mode: true
    transparency_off: false
sideload_apps: true
developer_mode: true
# leave empty if no change needed
device_name:
wallpaper_full_path:
# add exact choco package names to install, some examples are listed
choco_apps:
    - test-bla-nonexistent-package
    # - 7zip.install
    # - keepassxc
    # - git
    # - ojdkbuild8
    # - ojdkbuild11
    # - brave
    # - notepadplusplus
    # - authy-desktop
    # - processhacker
    # - intellijidea-ultimate
    # - intellijidea-community
    # - eclipse
